_BASE_: "../Base-DensePose-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "/share/home/liuqiong/sunjunyao/detectron2/projects/DensePose/tmp/hrnetv2_w32_imagenet_pretrained.pth"
  BACKBONE:
    NAME: "build_hrfpn_backbone"
  RPN:
    IN_FEATURES: ['p1', 'p2', 'p3', 'p4', 'p5']
  ROI_HEADS:
    IN_FEATURES: ['p1', 'p2', 'p3', 'p4', 'p5']
SOLVER:
  MAX_ITER: 180000
  STEPS: (120000, 160000)
  IMS_PER_BATCH: 8
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "norm"
  BASE_LR: 0.03
