model:
  base_learning_rate: 2.0e-06
  target: densepose.modeling.ldm.ddpm.LatentDiffusion
  params:
    ckpt_path: "/share/home/liuqiong/sunjunyao/detectron2/projects/DensePose/tmp/ldm/latent-diffusion-200k.ckpt"
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    image_size: 28
    channels: 3
    pds: True
    unet_config:
      target: densepose.modeling.ldm.modules.openaimodel.UNetModel
      params:
        image_size: 28
        in_channels: 3
        out_channels: 3
        model_channels: 224
        attention_resolutions:
        - 4
        - 2
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 3
        num_head_channels: 32
    first_stage_config:
      target: densepose.modeling.ldm.autoencoder.AutoencoderKL
      params:
        ckpt_path: "/share/home/liuqiong/sunjunyao/detectron2/projects/DensePose/tmp/ldm/encoder-iuv.ckpt"
        embed_dim: 3
        ddconfig:
          double_z: True
          z_channels: 3
          resolution: 112
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
    cond_stage_config: __is_unconditional__