_BASE_: "Base-DensePose-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "/share/home/liuqiong/sunjunyao/detectron2/projects/DensePose/tmp/R-101.pkl"
  RESNETS:
    DEPTH: 101
SOLVER:
  MAX_ITER: 180000
  STEPS: (120000, 160000)
  IMS_PER_BATCH: 16
OUTPUT_DIR: "./output/densepose_R_101_FPN_s1x/"
