_BASE_: "Base-DensePose-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "/share/home/liuqiong/sunjunyao/detectron2/projects/DensePose/tmp/R-50.pkl"
  RESNETS:
    DEPTH: 50
SOLVER:
  MAX_ITER: 180000
  STEPS: (120000, 160000)
  # IMS_PER_BATCH: 8
OUTPUT_DIR: "./output/densepose_R_50_FPN_s1x/"
