_BASE_: "Base-DensePose-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "/share/home/liuqiong/sunjunyao/detectron2/projects/DensePose/tmp/R-50.pkl"
  DENSEPOSE_SDS_ON: True
  RESNETS:
    DEPTH: 50
  ROI_DENSEPOSE_HEAD:
    DECODER_ON: False
  ROI_DENSEPOSE_SDS_HEAD:
    SDS_LOSS_WEIGHT: 0.001
    USE_IMAGE_AS_COND: True
    CFGDIR: "./configs/ldm/ldm-kl-112x112x3-cond.yaml"
SOLVER:
  MAX_ITER: 180000
  STEPS: (120000, 160000)
  IMS_PER_BATCH: 16
OUTPUT_DIR: "./output/densepose_R_50_s1x_sds-image/"
